---
title: Analytics Report Shell
author: 
  - name: Joshua, Albert
    email: joshua.albert@snhu.edu
    affiliations: 
      - name: Southern New Hampshire University
date: today
date-format: long
theme: flatly
toc: true
---

```{r global-options, include=FALSE}
library(tidyverse)
library(tidymodels)
library(patchwork)
library(kableExtra)

options(kable_styling_bootstrap_options = c("hover", "striped"))

theme_set(theme_bw(base_size = 14))
```

## Statement of Purpose
```{r}
competion <- read.csv("https://raw.githubusercontent.com/joshalbert16/MAT434/refs/heads/main/comp.csv?token=GHSAT0AAAAAAC5CLRCSK23Q2EW2RRY77D6OZ4J5O7A")

data <- read.csv("https://raw.githubusercontent.com/joshalbert16/MAT434/refs/heads/main/data.csv?token=GHSAT0AAAAAAC5CLRCTV5WGE44EZA327DPAZ4J5PWA")

```



## Executive Summary
```{r}
competion %>%
  head()

data %>%
  head()
```



## Introduction



## Exploratory Data Analysis
  


## Model Construction



## Model Interpretation and Inference



## Conclusion



## References
```{r}



```

You can add options to executable code like this

```{r}


```


