---
title: "PCA_DimensionReduction"
format: html
---

```{r}
library(tidyverse)
library(tidymodels)
library(ggforce)
```

```{r}

data <- read_csv("https://raw.githubusercontent.com/agmath/agmath.github.io/master/data/classification/cancer_gene_expression_data.csv")

set.seed(222)
data_splits <- initial_split(data)

train <- training(data_splits)
test <- testing(data_splits)


```

```{r}

train %>% 
  count(labels)


```


```{r}
train %>%
  select(1:5, 2502) %>%
    ggplot(aes(x = .panel_x, y = .panel_y, color = labels, fill = labels)) +
    geom_point() +
    geom_autodensity(alpha = .3) +
    facet_matrix(vars(-labels), layer.diag = 2) + 
    scale_color_brewer(palette = "Dark2") + 
    scale_fill_brewer(palette = "Dark2")
```

```{r}

pca_rec <- recipe(labels ~ ., data = train) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_pca(all_numeric_predictors())

pca_rec %>% 
  prep() %>% 
  tidy(number = 3, type = "variance") %>% 
  filter(terms == "percent variance") %>% 
  mutate(total_variance = cumsum(value))

```

```{r}
pca_rec <- recipe(labels ~ ., data = train) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_pca(all_numeric_predictors(), num_comp = 5)

pca_rec %>% 
  prep() %>% 
  tidy(number = 3, type = "variance") %>% 
  filter(terms == "percent variance") %>% 
  mutate(total_variance = cumsum(value))

train_baked <- pca_rec %>% 
  prep() %>% 
  bake(train)
```

```{r}

pca_rec %>% 
  prep() %>% 
  bake(train) %>% 
ggplot(aes(x = .panel_x, y = .panel_y, color = labels, fill = labels)) +
    geom_point() +
    geom_autodensity(alpha = .3) +
    facet_matrix(vars(-labels), layer.diag = 2) + 
    scale_color_brewer(palette = "Dark2") + 
    scale_fill_brewer(palette = "Dark2")
```


